### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'insertAfter')

### ISSUE THREAD

**Issue by BleedingDev** [rspack-contrib/rsbuild-plugin-tailwindcss#16]
Hi,
I tried to use this plugin and it fails with following error:

```bash
start   Building...
<e> [webpack-dev-middleware] [Error:   × TypeError: Cannot read properties of undefined (reading 'insertAfter')
<e>   │     at Root.after (D:\Side\nmit-coursition\node_modules\.pnpm\rsbuild-plugin-tailwindcss@0.0.2_@rsbuild+core@1.1.3_tailwindcss@3.4.15_ts-node@10.9.2_@swc+c_iea46vmxfpnftq2zpelg5joqme\node_modules\rsbuild-plugin-tailwindcss\dist\880.cjs:1633:29)
<e>   │     at partitionRules (D:\Side\nmit-coursition\node_modules\.pnpm\tailwindcss@3.4.15_ts-node@10.9.2_@swc+core@1.5.25_@swc+helpers@0.5.15__@types+node@20.17.6_typescript@5.6.3_\node_modules\tailwindcss\lib\lib\partitionApplyAtRules.js:49:18)
<e>   │     at D:\Side\nmit-coursition\node_modules\.pnpm\tailwindcss@3.4.15_ts-node@10.9.2_@swc+core@1.5.25_@swc+helpers@0.5.15__@types+node@20.17.6_typescript@5.6.3_\node_modules\tailwindcss\lib\lib\partitionApplyAtRules.js:56:9
<e>   │     at D:\Side\nmit-coursition\node_modules\.pnpm\tailwindcss@3.4.15_ts-node@10.9.2_@swc+core@1.5.25_@swc+helpers@0.5.15__@types+node@20.17.6_typescript@5.6.3_\node_modules\tailwindcss\lib\processTailwindFeatures.js:54:46
<e>   │     at async plugins (D:\Side\nmit-coursition\node_modules\.pnpm\tailwindcss@3.4.15_ts-node@10.9.2_@swc+core@1.5.25_@swc+helpers@0.5.15__@types+node@20.17.6_typescript@5.6.3_\node_modules\tailwindcss\lib\plugin.js:38:17)
<e>   │     at async LazyResult.runAsync (D:\Side\nmit-coursition\node_modules\.pnpm\rsbuild-plugin-tailwindcss@0.0.2_@rsbuild+core@1.1.3_tailwindcss@3.4.15_ts-node@10.9.2_@swc+c_iea46vmxfpnftq2zpelg5joqme\node_modules\rsbuild-plugin-tailwindcss\dist\880.cjs:949:25)      
<e>   │     at async D:\Side\nmit-coursition\node_modules\.pnpm\rsbuild-plugin-tailwindcss@0.0.2_@rsbuild+core@1.1.3_tailwindcss@3.4.15_ts-node@10.9.2_@swc+c_iea46vmxfpnftq2zpelg5joqme\node_modules\rsbuild-plugin-tailwindcss\dist\index.cjs:268:49
<e>   │     at async Promise.all (index 0)
<e>   │     at async D:\Side\nmit-coursition\node_modules\.pnpm\rsbuild-plugin-tailwindcss@0.0.2_@rsbuild+core@1.1.3_tailwindcss@3.4.15_ts-node@10.9.2_@swc+c_iea46vmxfpnftq2zpelg5joqme\node_modules\rsbuild-plugin-tailwindcss\dist\index.cjs:264:21
<e>   │     at async Promise.all (index 0)
<e>   │     at async Object.fn (D:\Side\nmit-coursition\node_modules\.pnpm\rsbuild-plugin-tailwindcss@0.0.2_@rsbuild+core@1.1.3_tailwindcss@3.4.15_ts-node@10.9.2_@swc+c_iea46vmxfpnftq2zpelg5joqme\node_modules\rsbuild-plugin-tailwindcss\dist\index.cjs:237:17)
<e>   │ 
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

Anything I should do differently? :) I am trying to consume UI Library (Shadcn) and also use styles in the app (I have Nx Monorepo, which I can share).

**Comment by colinaaa** [comment]
Hi @BleedingDev, it would be great if you could provide the repo that can re-produce this problem

**Comment by BleedingDev** [comment]
Sure thing, I'll try to do minimal reproduction example, sorry for not adding it immediately.

**Comment by colinaaa** [comment]
Hi @BleedingDev, I would be able to reproduce this with a [minimal reproduction](https://github.com/colinaaa-reproductions/rsbuild-plugin-tailwindcss-issue-16).

It seems like the `lightningcss-loader` of Rspack is transforming

```css
@layer base {
  * {
    @apply rounded-none;
  }
}
```

into

```css
@layer base {
  @apply rounded-none;
}
```

which makes Tailwind CSS not working.

You may temporarily disable `lightningcss-loader` by setting [`tools.lightningcssLoader`](https://rsbuild.dev/config/tools/lightningcss-loader#disable-loader) to `false`.

We would make more investigation on this issue(maybe disable `tools.lightningcssLoader` in rsbuild-plugin-tailwindcss).

Thank you for your reporting.

**Comment by rogerleung0411** [comment]
I encountered the same error. Strangely, in my monorepo, two apps have almost the same configuration, but only one of the apps will throw such an error. Luckily enough setting [tools.lightningcssLoader](https://rsbuild.dev/config/tools/lightningcss-loader#disable-loader) to false works.

**Comment by rogerleung0411** [comment]
hi @colinaaa, i notice that rsbuild work perfectly without this plugin even not explicitly set [tools.lightningcssLoader](https://rsbuild.dev/config/tools/lightningcss-loader#disable-loader) to false. what's the difference between these use cases?

my repro demo is here:
https://github.com/rogerleung0411/rsbuild-plugin-tailwindcss-issue/blob/d8b8d484939ff16bc671d5c5faf08a405c403e10/rsbuild.config.ts#L8-L15

**Comment by colinaaa** [comment]
@rogerleung0411 The same reason as I mentioned before:

> It seems like the `lightningcss-loader` of Rspack is transforming
> 
> ```css
> @layer base {
>   * {
>     @apply rounded-none;
>   }
> }
> ```
>
> into
> 
> ```css
> @layer base {
>   @apply rounded-none;
> }
> ```
>
> which makes Tailwind CSS not working.

BTW, you could check the [Loader Analysis](https://rsdoctor.dev/blog/topic/loader-optimization#analyzing-files) of Rsdoctor for yourself:

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/c2d9a6b2-9051-48fb-91a8-d57185162ad8" />

**Comment by colinaaa** [comment]
When using directly with Rsbuild, the `@layer` and `@apply` are transformed by PostCSS directly:

<img width="1039" alt="Image" src="https://github.com/user-attachments/assets/d9d65050-79ec-47ce-a14d-2e15a9ac1ac3" />

**Comment by chenjiahan** [comment]
@colinaaa I suppose we should run Tailwind CSS before the Lightning CSS transform.: https://github.com/parcel-bundler/lightningcss/issues/896#issuecomment-2609900144

**Comment by colinaaa** [comment]
> [@colinaaa](https://github.com/colinaaa) I suppose we should run Tailwind CSS before the Lightning CSS transform: [parcel-bundler/lightningcss#896 (comment)](https://github.com/parcel-bundler/lightningcss/issues/896#issuecomment-2609900144)

I don't think we can do that without disabling builtin:lightningcss-loader. Since we remove the `tailwindcss` from postcss.plugins and transform `@tailwind` during `processAssets`.
